import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import ReduxProvider from "./ReduxProvider";

const getHeaderData = async () => {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_BACKEND_URL}/api/web/get/header`,
      { next: { revalidate: 300 } }
    );
    if (!response.ok) {
      throw new Error("Failed to fetch data");
    }
    const data = await response.json();
    return data?.data || [];
  } catch (error) {
    return [];
  }
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const headerData = await getHeaderData();

  return (
    <html lang="en">
      <body className="antialiased">
        <ReduxProvider>
          <Header headerData={headerData} />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
